import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
    await prisma.technology.createMany({
        data: [
            { name: 'React' },
            { name: 'Angular' },
            { name: 'Vue.js' },
            { name: 'Express.js' },
            { name: 'Next.js' },
            { name: 'Nuxt.js' },
            { name: 'Svelte' },
            { name: 'Django' },
            { name: 'Flask' },
            { name: 'Spring Boot' },
            { name: 'ASP.NET' },
            { name: 'Ruby on Rails' },
            { name: 'Laravel' },
            { name: 'Symfony' },
            { name: 'CodeIgniter' },
            { name: 'CakePHP' },
            { name: 'Zend Framework' },
            { name: 'Struts' },
            { name: 'Koa.js' },
            { name: 'Meteor.js' },
            { name: 'Deno' },
            { name: 'NestJS' },
            { name: 'AdonisJS' },
            { name: 'Feathers.js' },
            { name: 'Hapi.js' },
            { name: 'LoopBack' },
            { name: 'Socket.io' },
            { name: 'GraphQL' },
            { name: 'RESTful API' },
            { name: 'JSON Web Tokens (JWT)' },
            { name: 'OAuth' },
            { name: 'Firebase' },
            { name: 'AWS Lambda' },
            { name: 'Google Cloud Functions' },
            { name: 'Azure Functions' },
            { name: 'Heroku' },
            { name: 'Netlify' },
            { name: 'Vercel' },
            { name: 'Webpack' },
            { name: 'Babel' },
            { name: 'TypeScript' },
            { name: 'JavaScript' },
            { name: 'HTML' },
            { name: 'CSS' },
            { name: 'Sass' },
            { name: 'Less' },
            { name: 'Tailwind CSS' },
            { name: 'Bootstrap' },
            { name: 'Foundation' },
            { name: 'Material-UI' },
            { name: 'Ant Design' },
            { name: 'Chakra UI' },
            { name: 'Jest' },
            { name: 'Mocha' },
            { name: 'Chai' },
            { name: 'Cypress' },
            { name: 'Enzyme' },
            { name: 'React Testing Library' },
            { name: 'Vue Test Utils' },
            { name: 'PHPUnit' },
            { name: 'Codeception' },
            { name: 'Karma' },
            { name: 'Jasmine' },
            { name: 'Protractor' },
            { name: 'Nightwatch.js' },
            { name: 'Storybook' },
            { name: 'Apollo Server' },
            { name: 'Prisma' },
            { name: 'Sequelize' },
            { name: 'Mongoose' },
            { name: 'Knex.js' },
            { name: 'Doctrine' },
            { name: 'Hibernate' },
            { name: 'Entity Framework' },
            { name: 'SQLAlchemy' },
            { name: 'Bookshelf.js' },
            { name: 'Active Record' },
            { name: 'TypeORM' },
            { name: 'Fluent NHibernate' },
            { name: 'MyBatis' },
            { name: 'Ibatis' },
            { name: 'Nhibernate' },
            { name: 'SqlKata' },
            { name: 'Lodash' },
            { name: 'Underscore.js' },
            { name: 'Ramda' },
            { name: 'RxJS' },
            { name: 'Redux' },
            { name: 'MobX' },
            { name: 'Vuex' },
            { name: 'Flux' },
            { name: 'Context API' },
            { name: 'React Router' },
            { name: 'Vue Router' },
            { name: 'React Native' },
            { name: 'Ionic' },
            { name: 'Flutter' },
            { name: 'PostgreSQL' } 
        ]
    });
}

main()
    .catch((error) => {
        console.error(error);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
